name = "Shiro neeko"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "9190a3b1-ab4f-42ef-a9af-541f3e89231a"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
