name = "shiro"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "7924bcb0-3338-46d5-97c6-831057dbe3d1"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
